version: '3.3'

services:

#  coturn:
#    image: coturn/coturn
#    network_mode: host
#    volumes:
#      - ${PWD}/configs/coturn.conf:/etc/coturn/turnserver.conf
#      - ${PWD}/logs/:/var/log/

#  kurento:
#    image: kurento/kurento-media-server:7.0.0
#    network_mode: host
#    volumes:
#      - type: bind
#        source: /opt/om_data
#        target: /opt/om_data
#    environment:
#      #- KMS_TURN_URL=test:test@212.233.97.167:3478
#      - KMS_STUN_IP=212.233.97.167
#      - KMS_STUn_PORT=3478
#    depends_on:
#      - coturn

  openmeeting-test:
    build:
      context: om
      dockerfile: dockerfile
    network_mode: host
#    depends_on:
#      - coturn
#      - kurento
    environment:
 #     - OM_KURENTO_WS_URL=ws://127.0.0.1:8888/kurento
      - OM_DB_HOST=212.233.99.174
      - OM_DB_PORT=5432
      - OM_DB_TYPE=postgresql
      - OM_DB_USER=openmeetings
      - OM_DB_NAME=openmeetings
      - OM_DB_PASS=Timon.pumba4ever
#      - TURN_URL=212.233.97.167:3478
      #- TURN_PASS=dec4b8dd6b8e79623bd1409cfab637254695586bae247785c9426f11ece87feb
      #- TURN_PASS=test
      #- TURN_USER=test

#  openmeeting:
#    image: apache/openmeetings:min-7.2.0
#    environme:
#      - OM_KURENTO_WS_URL="ws://localhost:8888/kurento"
#      - OM_DB_HOST="212.233.99.174"
#      - OM_DB_USER="openmeetings"
#      - OM_DB_NAME="openmeetings"
#      - OM_DB_PASS="Timon&&pumba4ever"
#      - DB_ROOT_PASS="Timon&&pumba4ever"
#      - TURN_URL="212.233.97.167:3478"
#      - TURN_USER="test"
#      - TURN_PASS="test12"
#    depends_on:
#      - kurento
#    ports:
#      - 5443:5443
