version: '3.3'

services:

  coturn:
    image: coturn/coturn
    network_mode: host
    volumes:
      - ${PWD}/configs/coturn.conf:/etc/coturn/turnserver.conf

  kurento:
    image: kurento/kurento-media-server:7.0.0
    environment:
      - KMS_MIN_PORT=5000
      - KMS_MAX_PORT=5050
    network_mode: host
    depends_on:
      - coturn

#  openmeeting:
#    build:
#      context: .
#      dockerfile: dockerfile-openmeeting
#    network_mode: host 
   # ports:
   #   - "5443:5443"
#    command: /etc/init.d/tomcat34 start
#    depends_on:
#      - coturn
#      - kurento

  openmeeting-test:
    build:
      context: om
      dockerfile: dockerfile
    network_mode: host
    depends_on:
      - coturn
      - kurento
    environment:
      - OM_KURENTO_WS_URL=ws://127.0.0.1:8888/kurento
      - OM_DB_HOST=127.0.0.1
      - OM_DB_PORT=5432
      - OM_DB_TYPE=postgresql
      - OM_DB_USER=postgres
      - OM_DB_NAME=postgres
      - OM_DB_PASS=postgres
      - TURN_URL=212.233.97.167:3478
      - TURN_USER=test
      - TURN_PASS=test12


#  openmeeting:
#    image: apache/openmeetings:min-7.2.0
#    environme:
#      - OM_KURENTO_WS_URL="ws://localhost:8888/kurento"
#      - OM_DB_HOST="212.233.99.174"
#      - OM_DB_USER="openmeetings"
#      - OM_DB_NAME="openmeetings"
#      - OM_DB_PASS="Timon&&pumba4ever"
#      - DB_ROOT_PASS="Timon&&pumba4ever"
#      - TURN_URL="212.233.97.167:3478"
#      - TURN_USER="test"
#      - TURN_PASS="test12"
#    depends_on:
#      - kurento
#    ports:
#      - 5443:5443
